apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: quandl
      hasuraService: custom
    name: quandl
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: quandl
      spec:
        containers:
        - image: hasura/base-git-image:0.7
          env:
          - name: QUANDL_API_KEY
            valueFrom:
              secretKeyRef:
                key: quandl.api.key
                name: hasura-secrets
          imagePullPolicy: IfNotPresent
          name: quandl
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: quandl
      hasuraService: custom
    name: quandl
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: quandl
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
