apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: metabase
      hasuraService: custom
    name: metabase
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: metabase
      spec:
        containers:
        - image: metabase/metabase:latest
          env:
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_DBNAME
              value: hasuradb
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  key: postgres.user
                  name: hasura-secrets
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: postgres.password
                  name: hasura-secrets
            - name: MB_DB_HOST
              value: postgres.hasura
          imagePullPolicy: IfNotPresent
          name: metabase
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: metabase
      hasuraService: custom
    name: metabase
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: metabase
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
